[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 9600
lib_deps = 
	ottowinter/ESPAsyncWebServer-esphome@3.4.0
	bblanchon/ArduinoJson@7.2.2
	bblanchon/StreamUtils@1.9.2