[platformio]
extra_configs = platformio_secrets.ini

[env:esp32dev]
platform = espressif32 @ 6.5.0
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 9600
lib_deps = 
	bblanchon/ArduinoJson @ 7.2.2
	duinoWitchery/hd44780 @ ^1.3.2